---
  - name: "Playing with Ansible and Git"
    hosts: localhost
    connection: local 
    tasks:

    - name: Install Git
      become: true
      ansible.builtin.package:
        state: present
        name: git

    - name: Install ZSH
      become: true
      ansible.builtin.package:
        name: zsh
        state: present

    - name: Install unzip
      become: true
      ansible.builtin.package:
        state: present
        name: unzip

    - name: Install exa
      become: true
      ansible.builtin.package:
        state: present
        name: exa

    - name: Install ripgrep
      become: true
      ansible.builtin.package:
        state: present
        name: ripgrep

    - name: Install fd-find
      become: true
      ansible.builtin.package:
        state: present
        name: "fd-find"

    - name: Create link fd to fdfind in Debian
      become: true
      ansible.builtin.file:
        src: '/usr/bin/fdfind'
        dest: '/usr/bin/fd'
        state: link
      when: ansible_os_family == 'Debian'

    - name: Install bat
      become: true
      ansible.builtin.package:
        state: present
        name: bat
     
    - name: Create link bat to batcat in Debian
      become: true
      ansible.builtin.file:
        src: '/usr/bin/batcat'
        dest: '/usr/bin/bat'
        state: link
      when: ansible_os_family == 'Debian' and ansible_distribution_version is version('23.04', '<')

    - name: Change user shell to zsh 
      become: true
      ansible.builtin.user:
        name: "{{ ansible_user_id }}"
        shell: /bin/zsh

    - name: Install nvim [snap] 
      become: false
      community.general.snap:
        name: nvim
        classic: yes

    - name: Install xclip
      become: true
      ansible.builtin.package:
        state: present
        name: xclip

    - name: Install stow
      become: true
      ansible.builtin.package:
        state: present
        name: stow
